name: Rust CI

on: [push, pull_request]

jobs:
  test_native:
    name: Test Rust Native
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test native target
        run: cargo test --verbose
      - name: Test native target (only cloud integration tests)
        run: |
          cargo test -p assemblage_db -p assemblage_view -p assemblage_broadcast \
          --verbose --features assemblage-broadcast-integration-tests
  test_wasm:
    name: Test Rust WASM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install wasm-pack
        run: |
          curl https://raw.githubusercontent.com/rustwasm/wasm-pack/master/docs/_installer/init.sh -sSf \
          | sed -e 's/$VERSION/v0.9.1/g' \
          | sh
      - name: Test wasm target (assemblage_kv)
        run: wasm-pack test --headless --chrome --firefox assemblage_kv
      - name: Test wasm target (assemblage_db)
        run: wasm-pack test --headless --chrome --firefox assemblage_db
      - name: Test wasm target (assemblage_view)
        run: wasm-pack test --headless --chrome --firefox assemblage_view
      - name: Test wasm target (assemblage_db, only cloud integration tests)
        run: |
          WASM_BINDGEN_TEST_TIMEOUT=300 wasm-pack test --headless --chrome --firefox \
          assemblage_db -- --features assemblage-broadcast-integration-tests
      - name: Test wasm target (assemblage_view, only cloud integration tests)
        run: |
          WASM_BINDGEN_TEST_TIMEOUT=300 wasm-pack test --headless --chrome --firefox \
          assemblage_view -- --features assemblage-broadcast-integration-tests
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run clippy
        run: cargo clippy --all-targets -- -Dclippy::all
